import { Product } from './types';

export const HALAL_STATUSES = ['Certified', 'Self-Certified', 'Shariah-Compliant'] as const;

const now = Date.now();
const today = new Date().toISOString();
const yesterday = new Date(now - 86400000).toISOString();
const lastWeek = new Date(now - 4 * 86400000).toISOString();
const lastMonth = new Date(now - 20 * 86400000).toISOString();

export const INITIAL_PRODUCTS: Product[] = [
  // --- TODAY (10 Products) ---
  {
    id: 't1',
    created_at: today,
    name: 'QuranFlow 2.0',
    description: 'A beautiful, distraction-free Quran reading experience with habit tracking and professional recitations.',
    tagline: 'Build a meaningful relationship with the Quran.',
    url: 'https://example.com/quranflow',
    logo_url: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=128&h=128&fit=crop',
    founder_id: 'u_1',
    category: 'Spirituality',
    upvotes_count: 542,
    halal_status: 'Certified'
  },
  {
    id: 't2',
    created_at: today,
    name: 'ArabicHero',
    description: 'Gamified Arabic learning for kids and adults. Master the language of the Quran through interactive stories.',
    tagline: 'Master Arabic through play.',
    url: 'https://example.com/arabichero',
    logo_url: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=128&h=128&fit=crop',
    founder_id: 'u_2',
    category: 'Education',
    upvotes_count: 489,
    halal_status: 'Self-Certified'
  },
  {
    id: 't3',
    created_at: today,
    name: 'Muslim CRM',
    description: 'Specialized CRM for NGOs and Mosques to manage donors and community engagement.',
    tagline: 'Empowering community growth through data.',
    url: 'https://logo.clearbit.com/salesforce.com',
    logo_url: 'https://logo.clearbit.com/salesforce.com',
    founder_id: 'u_3',
    category: 'Productivity',
    upvotes_count: 412,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 't4',
    created_at: today,
    name: 'Halal Ad Network',
    description: 'The first ethical advertising platform filtering for Halal-only brands.',
    tagline: 'Ethical reach for your brand.',
    url: 'https://logo.clearbit.com/google.com',
    logo_url: 'https://logo.clearbit.com/google.com',
    founder_id: 'u_4',
    category: 'Marketing',
    upvotes_count: 395,
    halal_status: 'Certified'
  },
  {
    id: 't5',
    created_at: today,
    name: 'Prayer Time API',
    description: 'High-precision, globally distributed API for prayer timings and Qibla direction.',
    tagline: 'Reliable data for your next Deen app.',
    url: 'https://logo.clearbit.com/stripe.com',
    logo_url: 'https://logo.clearbit.com/stripe.com',
    founder_id: 'u_5',
    category: 'Engineering',
    upvotes_count: 358,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 't6',
    created_at: today,
    name: 'SunnahHabit',
    description: 'A micro-habit tracker based on the prophetic traditions (Sunnah).',
    tagline: 'Better yourself, one sunnah at a time.',
    url: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=128&h=128&fit=crop',
    logo_url: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=128&h=128&fit=crop',
    founder_id: 'u_6',
    category: 'Spirituality',
    upvotes_count: 320,
    halal_status: 'Self-Certified'
  },
  {
    id: 't7',
    created_at: today,
    name: 'MasjidFinder Pro',
    description: 'Find Mosques near you with detailed info on facilities like Wudu areas and parking.',
    tagline: 'Never miss a Jamaat again.',
    url: 'https://logo.clearbit.com/airbnb.com',
    logo_url: 'https://logo.clearbit.com/airbnb.com',
    founder_id: 'u_7',
    category: 'Travel',
    upvotes_count: 284,
    halal_status: 'Certified'
  },
  {
    id: 't8',
    created_at: today,
    name: 'ZakatStream',
    description: 'Real-time Zakat calculation integrated with your banking APIs.',
    tagline: 'Simplified wealth purification.',
    url: 'https://logo.clearbit.com/wealthsimple.com',
    logo_url: 'https://logo.clearbit.com/wealthsimple.com',
    founder_id: 'u_8',
    category: 'Finance',
    upvotes_count: 265,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 't9',
    created_at: today,
    name: 'HalalFoodie',
    description: 'Community-vetted restaurant directory with verified Halal certification images.',
    tagline: 'Eat with confidence.',
    url: 'https://logo.clearbit.com/yelp.com',
    logo_url: 'https://logo.clearbit.com/yelp.com',
    founder_id: 'u_9',
    category: 'Food',
    upvotes_count: 241,
    halal_status: 'Certified'
  },
  {
    id: 't10',
    created_at: today,
    name: 'UmmahConnect',
    description: 'A professional network for Muslim developers and entrepreneurs.',
    tagline: 'The LinkedIn for the Ummah.',
    url: 'https://logo.clearbit.com/linkedin.com',
    logo_url: 'https://logo.clearbit.com/linkedin.com',
    founder_id: 'u_10',
    category: 'Social',
    upvotes_count: 212,
    halal_status: 'Self-Certified'
  },

  // --- YESTERDAY (10 Products) ---
  {
    id: 'y1',
    created_at: yesterday,
    name: 'NikahMatch',
    description: 'The most privacy-focused matrimonial app for practicing Muslims.',
    tagline: 'Finding your half, the Halal way.',
    url: 'https://logo.clearbit.com/bumble.com',
    logo_url: 'https://logo.clearbit.com/bumble.com',
    founder_id: 'u_11',
    category: 'Social',
    upvotes_count: 489,
    halal_status: 'Certified'
  },
  {
    id: 'y2',
    created_at: yesterday,
    name: 'HajjGuide AI',
    description: 'Interactive AI companion for pilgrims during Hajj and Umrah.',
    tagline: 'Your digital guide to the holy cities.',
    url: 'https://logo.clearbit.com/duolingo.com',
    logo_url: 'https://logo.clearbit.com/duolingo.com',
    founder_id: 'u_12',
    category: 'Travel',
    upvotes_count: 452,
    halal_status: 'Certified'
  },
  {
    id: 'y3',
    created_at: yesterday,
    name: 'HalalWallet',
    description: 'Track your expenses and investments while filtering for Shariah compliance.',
    tagline: 'Purify your portfolio.',
    url: 'https://logo.clearbit.com/mint.com',
    logo_url: 'https://logo.clearbit.com/mint.com',
    founder_id: 'u_13',
    category: 'Finance',
    upvotes_count: 398,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 'y4',
    created_at: yesterday,
    name: 'MuslimMind',
    description: 'Mental health and mindfulness rooted in Islamic principles.',
    tagline: 'Find peace through prayer and practice.',
    url: 'https://logo.clearbit.com/headspace.com',
    logo_url: 'https://logo.clearbit.com/headspace.com',
    founder_id: 'u_14',
    category: 'Health',
    upvotes_count: 367,
    halal_status: 'Certified'
  },
  {
    id: 'y5',
    created_at: yesterday,
    name: 'DeenJournal',
    description: 'A digital gratitude and reflection journal for daily Dhikr.',
    tagline: 'Reflect on your blessings daily.',
    url: 'https://logo.clearbit.com/dayoneapp.com',
    logo_url: 'https://logo.clearbit.com/dayoneapp.com',
    founder_id: 'u_15',
    category: 'Spirituality',
    upvotes_count: 342,
    halal_status: 'Self-Certified'
  },
  {
    id: 'y6',
    created_at: yesterday,
    name: 'SunnahSleep',
    description: 'Prophetic sleeping habits tracker with smart alarm integration.',
    tagline: 'Wake up for Fajr, every day.',
    url: 'https://logo.clearbit.com/sleepcycle.com',
    logo_url: 'https://logo.clearbit.com/sleepcycle.com',
    founder_id: 'u_16',
    category: 'Health',
    upvotes_count: 310,
    halal_status: 'Certified'
  },
  {
    id: 'y7',
    created_at: yesterday,
    name: 'ArabicFlash',
    description: 'Spaced-repetition flashcards for Quranic vocabulary.',
    tagline: 'Learn 80% of the Quran faster.',
    url: 'https://logo.clearbit.com/anki.net',
    logo_url: 'https://logo.clearbit.com/anki.net',
    founder_id: 'u_17',
    category: 'Education',
    upvotes_count: 288,
    halal_status: 'Certified'
  },
  {
    id: 'y8',
    created_at: yesterday,
    name: 'UmmahEvents',
    description: 'Discovery platform for local Islamic conferences and seminars.',
    tagline: 'Never miss an event in your community.',
    url: 'https://logo.clearbit.com/eventbrite.com',
    logo_url: 'https://logo.clearbit.com/eventbrite.com',
    founder_id: 'u_18',
    category: 'Social',
    upvotes_count: 256,
    halal_status: 'Self-Certified'
  },
  {
    id: 'y9',
    created_at: yesterday,
    name: 'HalalInvest',
    description: 'Stock filtering tool to ensure your investments are interest-free.',
    tagline: 'Investing made simple and Halal.',
    url: 'https://logo.clearbit.com/robinhood.com',
    logo_url: 'https://logo.clearbit.com/robinhood.com',
    founder_id: 'u_19',
    category: 'Finance',
    upvotes_count: 220,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 'y10',
    created_at: yesterday,
    name: 'QuranicTutor',
    description: 'Marketplace to find verified Tajweed and Hifz teachers globally.',
    tagline: 'The perfect teacher for your journey.',
    url: 'https://logo.clearbit.com/preply.com',
    logo_url: 'https://logo.clearbit.com/preply.com',
    founder_id: 'u_20',
    category: 'Education',
    upvotes_count: 195,
    halal_status: 'Certified'
  },

  // --- LAST WEEK (10 Products) ---
  {
    id: 'w1',
    created_at: lastWeek,
    name: 'EthicalCode',
    description: 'A platform to help developers vet the ethics of their code dependencies.',
    tagline: 'Build responsible software.',
    url: 'https://logo.clearbit.com/github.com',
    logo_url: 'https://logo.clearbit.com/github.com',
    founder_id: 'u_21',
    category: 'Engineering',
    upvotes_count: 312,
    halal_status: 'Certified'
  },
  {
    id: 'w2',
    created_at: lastWeek,
    name: 'FajrFocus',
    description: 'Productivity tool that schedules your deep work around prayer times.',
    tagline: 'Align your work with your worship.',
    url: 'https://logo.clearbit.com/notion.so',
    logo_url: 'https://logo.clearbit.com/notion.so',
    founder_id: 'u_22',
    category: 'Productivity',
    upvotes_count: 289,
    halal_status: 'Self-Certified'
  },
  {
    id: 'w3',
    created_at: lastWeek,
    name: 'ZakatFund',
    description: 'Direct Zakat distribution platform with 100% transparency.',
    tagline: 'Track every cent of your charity.',
    url: 'https://logo.clearbit.com/gofundme.com',
    logo_url: 'https://logo.clearbit.com/gofundme.com',
    founder_id: 'u_23',
    category: 'Finance',
    upvotes_count: 265,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 'w4',
    created_at: lastWeek,
    name: 'ArabicCalligraphy AI',
    description: 'Generative AI tool for creating stunning Arabic calligraphy art.',
    tagline: 'Beautiful art, created by you.',
    url: 'https://logo.clearbit.com/midjourney.com',
    logo_url: 'https://logo.clearbit.com/midjourney.com',
    founder_id: 'u_24',
    category: 'Design',
    upvotes_count: 245,
    halal_status: 'Certified'
  },
  {
    id: 'w5',
    created_at: lastWeek,
    name: 'IslamicHistory VR',
    description: 'Immersive VR experiences of historical Islamic sites.',
    tagline: 'Travel back in time to the Golden Age.',
    url: 'https://logo.clearbit.com/oculus.com',
    logo_url: 'https://logo.clearbit.com/oculus.com',
    founder_id: 'u_25',
    category: 'Education',
    upvotes_count: 220,
    halal_status: 'Certified'
  },
  {
    id: 'w6',
    created_at: lastWeek,
    name: 'DeenFit',
    description: 'Workout app with prayer-time integration and modest activewear deals.',
    tagline: 'Healthy body, healthy soul.',
    url: 'https://logo.clearbit.com/strava.com',
    logo_url: 'https://logo.clearbit.com/strava.com',
    founder_id: 'u_26',
    category: 'Health',
    upvotes_count: 198,
    halal_status: 'Self-Certified'
  },
  {
    id: 'w7',
    created_at: lastWeek,
    name: 'UmmahReads',
    description: 'A book club for the latest in Islamic literature and tech books.',
    tagline: 'Read together, grow together.',
    url: 'https://logo.clearbit.com/goodreads.com',
    logo_url: 'https://logo.clearbit.com/goodreads.com',
    founder_id: 'u_27',
    category: 'Education',
    upvotes_count: 175,
    halal_status: 'Certified'
  },
  {
    id: 'w8',
    created_at: lastWeek,
    name: 'ShariahPay',
    description: 'Merchant processing for interest-free transactions.',
    tagline: 'Pure payments for your business.',
    url: 'https://logo.clearbit.com/stripe.com',
    logo_url: 'https://logo.clearbit.com/stripe.com',
    founder_id: 'u_28',
    category: 'Finance',
    upvotes_count: 156,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 'w9',
    created_at: lastWeek,
    name: 'ArabicPodcast Hub',
    description: 'Curated directory of the best podcasts in Arabic and about Islam.',
    tagline: 'Listen and learn on the go.',
    url: 'https://logo.clearbit.com/spotify.com',
    logo_url: 'https://logo.clearbit.com/spotify.com',
    founder_id: 'u_29',
    category: 'Social',
    upvotes_count: 132,
    halal_status: 'Certified'
  },
  {
    id: 'w10',
    created_at: lastWeek,
    name: 'MuslimHome Pro',
    description: 'IoT integration for smart homes to sync Adhan and home lighting.',
    tagline: 'Your home, in sync with the Deen.',
    url: 'https://logo.clearbit.com/nest.com',
    logo_url: 'https://logo.clearbit.com/nest.com',
    founder_id: 'u_30',
    category: 'Productivity',
    upvotes_count: 112,
    halal_status: 'Self-Certified'
  },

  // --- LAST MONTH (10 Products) ---
  {
    id: 'notetaker-1',
    created_at: lastMonth,
    name: 'Notion',
    description: 'The all-in-one workspace for your notes, tasks, wikis, and databases.',
    tagline: 'Your connected workspace. Now with AI.',
    url: 'https://notion.so',
    logo_url: 'https://logo.clearbit.com/notion.so',
    founder_id: 'u_notion',
    category: 'AI notetakers',
    upvotes_count: 185,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 'm2',
    created_at: lastMonth,
    name: 'Muslim Travel Co',
    description: 'The premier travel agency for Halal-friendly luxury vacations.',
    tagline: 'Discover the world, Halal-style.',
    url: 'https://logo.clearbit.com/expedia.com',
    logo_url: 'https://logo.clearbit.com/expedia.com',
    founder_id: 'u_31',
    category: 'Travel',
    upvotes_count: 164,
    halal_status: 'Certified'
  },
  {
    id: 'm3',
    created_at: lastMonth,
    name: 'DeenGames',
    description: 'High-quality mobile games with positive Islamic values for children.',
    tagline: 'Play and learn values.',
    url: 'https://logo.clearbit.com/roblox.com',
    logo_url: 'https://logo.clearbit.com/roblox.com',
    founder_id: 'u_32',
    category: 'Education',
    upvotes_count: 142,
    halal_status: 'Self-Certified'
  },
  {
    id: 'm4',
    created_at: lastMonth,
    name: 'HalalStocks Pro',
    description: 'Advanced stock analysis tool for Shariah-compliant investors.',
    tagline: 'Smart data for ethical investing.',
    url: 'https://logo.clearbit.com/bloomberg.com',
    logo_url: 'https://logo.clearbit.com/bloomberg.com',
    founder_id: 'u_33',
    category: 'Finance',
    upvotes_count: 125,
    halal_status: 'Shariah-Compliant'
  },
  {
    id: 'm5',
    created_at: lastMonth,
    name: 'QuranAudio Pro',
    description: 'High-fidelity Quran recitations from top Qaris globally.',
    tagline: 'The most beautiful recitations in your pocket.',
    url: 'https://logo.clearbit.com/soundcloud.com',
    logo_url: 'https://logo.clearbit.com/soundcloud.com',
    founder_id: 'u_34',
    category: 'Spirituality',
    upvotes_count: 108,
    halal_status: 'Certified'
  },
  {
    id: 'm6',
    created_at: lastMonth,
    name: 'MuslimBaker',
    description: 'A platform for home bakers to sell verified Halal pastries locally.',
    tagline: 'Sweet treats, verified Halal.',
    url: 'https://logo.clearbit.com/etsy.com',
    logo_url: 'https://logo.clearbit.com/etsy.com',
    founder_id: 'u_35',
    category: 'Food',
    upvotes_count: 95,
    halal_status: 'Self-Certified'
  },
  {
    id: 'm7',
    created_at: lastMonth,
    name: 'SadaqahNow',
    description: 'Instant micro-charity donations for urgent global causes.',
    tagline: 'Give a little, help a lot.',
    url: 'https://logo.clearbit.com/paypal.com',
    logo_url: 'https://logo.clearbit.com/paypal.com',
    founder_id: 'u_36',
    category: 'Finance',
    upvotes_count: 82,
    halal_status: 'Certified'
  },
  {
    id: 'm8',
    created_at: lastMonth,
    name: 'IslamicLibrary',
    description: 'Access to thousands of digitized rare Islamic manuscripts.',
    tagline: 'Unlocking the wisdom of the past.',
    url: 'https://logo.clearbit.com/archive.org',
    logo_url: 'https://logo.clearbit.com/archive.org',
    founder_id: 'u_37',
    category: 'Education',
    upvotes_count: 76,
    halal_status: 'Certified'
  },
  {
    id: 'm9',
    created_at: lastMonth,
    name: 'HajjPrep VR',
    description: 'Simulate your Hajj journey in virtual reality before you fly.',
    tagline: 'Be prepared for the journey of a lifetime.',
    url: 'https://logo.clearbit.com/vive.com',
    logo_url: 'https://logo.clearbit.com/vive.com',
    founder_id: 'u_38',
    category: 'Travel',
    upvotes_count: 64,
    halal_status: 'Certified'
  },
  {
    id: 'm10',
    created_at: lastMonth,
    name: 'SunnahSkincare',
    description: 'All-natural, organic skincare based on ingredients from the Sunnah.',
    tagline: 'Pure beauty, pure ingredients.',
    url: 'https://logo.clearbit.com/glossier.com',
    logo_url: 'https://logo.clearbit.com/glossier.com',
    founder_id: 'u_39',
    category: 'Health',
    upvotes_count: 52,
    halal_status: 'Self-Certified'
  }
];

export const CATEGORIES = [
  'Spirituality',
  'Travel',
  'Finance',
  'Social',
  'Education',
  'Productivity',
  'Food',
  'Health',
  'AI notetakers',
  'Engineering',
  'Design',
  'Marketing'
];